- name: Deploy web servers
  hosts: webservers
  remote_user: ec2-user
  tasks:
    - name: Install git and python3
      become: true
      ansible.builtin.dnf:
        name: 
          - git
          - python3
        state: present

